apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-demo
  labels:
    app: cicd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-demo
  template:
    metadata:
      name: cicd-demo
      labels:
        app: cicd-demo
    spec:
      containers:
        - name: cicd-demo
          image: local/cicd-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8383
