name: CI Workflow

on:
  push:
    branches: [ main ] # Change this to your main branch name
  pull_request:
    branches: [ main ] # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Java 17

      - name: Build with Maven
        run: mvn clean package # Adjust this command based on your project requirements
